export const AVAILABLE_ROLES = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Data Analyst",
  "DevOps Engineer",
  "Mobile Developer",
  "Machine Learning Engineer",
] as const;

export const COMMON_SKILLS = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Express",
  "Python",
  "Java",
  "Spring Boot",
  "SQL",
  "MongoDB",
  "PostgreSQL",
  "Git",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "REST APIs",
  "GraphQL",
  "Testing",
  "CI/CD",
  "Agile",
  "TailwindCSS",
  "Redux",
  "Vue.js",
  "Angular",
  "Django",
  "Flask",
  "FastAPI",
  "C++",
  "C#",
  ".NET",
  "Ruby",
  "Ruby on Rails",
  "Go",
  "Rust",
  "PHP",
  "Laravel",
  "MySQL",
  "Redis",
  "Elasticsearch",
  "Microservices",
  "System Design",
  "Linux",
  "Bash",
  "PowerShell",
  "Jenkins",
  "GitHub Actions",
  "Terraform",
  "Ansible",
  "Machine Learning",
  "Deep Learning",
  "TensorFlow",
  "PyTorch",
  "Pandas",
  "NumPy",
  "Data Visualization",
  "Excel",
  "Power BI",
  "Tableau",
  "R",
  "Statistics",
  "Jupyter",
  "React Native",
  "Flutter",
  "Swift",
  "Kotlin",
  "Firebase",
  "Supabase",
  "Prisma",
  "Mongoose",
  "Webpack",
  "Vite",
  "ESLint",
  "Prettier",
  "Jest",
  "Cypress",
  "Selenium",
  "Postman",
  "Insomnia",
  "VS Code",
  "IntelliJ IDEA",
  "PyCharm",
  "Figma",
  "Adobe XD",
  "Sketch",
  "UI/UX Design",
  "Responsive Design",
  "Accessibility",
  "SEO",
  "Web Performance",
  "Security",
  "Authentication",
  "Authorization",
  "OAuth",
  "JWT",
  "WebSockets",
  "gRPC",
  "Nginx",
  "Apache",
  "Load Balancing",
  "Caching",
  "CDN",
  "Monitoring",
  "Logging",
  "Debugging",
  "Problem Solving",
  "Communication",
  "Teamwork",
  "Leadership",
  "Project Management",
  "Scrum",
  "Kanban",
] as const;
